INSERT INTO cars (brand, model, car_type, capacity, transmission_type, pick_up_location, drop_off_location,
                  price_per_day, img, created_at)
VALUES ('Toyota', 'Camry', 'MEDIUM', 5, 'AUTOMATIC', 'New York', 'New York', 50, 'camry.png', UNIX_TIMESTAMP()),
       ('Ford', 'Mustang', 'MEDIUM', 5, 'MANUAL', 'Chicago', 'Miami', 100, 'mustang.png', UNIX_TIMESTAMP()),
       ('Fiat', '500', 'SMALL', 4, 'AUTOMATIC', 'Los Angeles', 'Las Vegas', 75, 'fiat500.png', UNIX_TIMESTAMP()),
       ('Volkswagen', 'Touran', 'LARGE', 7, 'MANUAL', 'San Francisco', 'San Francisco', 85, 'touran.png',UNIX_TIMESTAMP()),
       ('Smart', 'Fortwo', 'SMALL', 2, 'AUTOMATIC', 'Chicago', 'Miami', 20, 'fortwo.png', UNIX_TIMESTAMP()),
       ('Honda', 'Civic', 'MEDIUM', 5, 'AUTOMATIC', 'New York', 'New York', 45, 'civic.png', UNIX_TIMESTAMP()),
       ('Chevrolet', 'Impala', 'LARGE', 5, 'AUTOMATIC', 'Los Angeles', 'Los Angeles', 70, 'impala.png',UNIX_TIMESTAMP()),
       ('Hyundai', 'Elantra', 'MEDIUM', 5, 'MANUAL', 'Chicago', 'Chicago', 40, 'elantra.png', UNIX_TIMESTAMP()),
       ('Peugeot', '208', 'SMALL', 4, 'MANUAL', 'Paris', 'Paris', 35, '208.png', UNIX_TIMESTAMP()),
       ('BMW', '3 Series', 'MEDIUM', 5, 'AUTOMATIC', 'Berlin', 'Berlin', 80, '3series.png', UNIX_TIMESTAMP()),
       ('Audi', 'A4', 'MEDIUM', 5, 'AUTOMATIC', 'London', 'London', 75, 'a4.png', UNIX_TIMESTAMP()),
       ('Seat', 'Ibiza', 'SMALL', 4, 'MANUAL', 'Madrid', 'Madrid', 30, 'ibiza.png', UNIX_TIMESTAMP()),
       ('Nissan', 'Altima', 'MEDIUM', 5, 'AUTOMATIC', 'Beijing', 'Beijing', 55, 'altima.png', UNIX_TIMESTAMP()),
       ('Kia', 'Optima', 'MEDIUM', 5, 'AUTOMATIC', 'Shanghai', 'Shanghai', 50, 'optima.png', UNIX_TIMESTAMP()),
       ('Mazda', '3', 'MEDIUM', 5, 'AUTOMATIC', 'Tokyo', 'Tokyo', 45, 'mazda3.png', UNIX_TIMESTAMP()),
       ('Subaru', 'Impreza', 'MEDIUM', 5, 'MANUAL', 'Osaka', 'Osaka', 40, 'impreza.png', UNIX_TIMESTAMP()),
       ('Volkswagen', 'Touran', 'LARGE', 7, 'MANUAL', 'New York', 'New York', 85, 'touran.png', UNIX_TIMESTAMP()),
       ('Mercedes-Benz', 'Vito', 'LARGE', 7, 'AUTOMATIC', 'Los Angeles', 'Los Angeles', 90, 'vito.png',UNIX_TIMESTAMP()),
       ('Citroen', 'Berlingo', 'LARGE', 7, 'MANUAL', 'Chicago', 'Chicago', 60, 'berlingo.png', UNIX_TIMESTAMP()),
       ('Peugeot', '5008', 'LARGE', 7, 'MANUAL', 'Paris', 'Paris', 70, '5008.png', UNIX_TIMESTAMP()),
       ('Renault', 'Espace', 'LARGE', 7, 'AUTOMATIC', 'Berlin', 'Berlin', 80, 'espace.png', UNIX_TIMESTAMP()),
       ('Smart', 'Fortwo', 'SMALL', 2, 'AUTOMATIC', 'London', 'London', 20, 'fortwo.png', UNIX_TIMESTAMP()),
       ('Fiat', '500', 'SMALL', 2, 'MANUAL', 'Madrid', 'Madrid', 30, 'fiat500.png', UNIX_TIMESTAMP()),
       ('Toyota', 'iQ', 'SMALL', 2, 'AUTOMATIC', 'Rome', 'Rome', 25, 'iq.png', UNIX_TIMESTAMP()),
       ('Renault', 'Twizy', 'SMALL', 2, 'AUTOMATIC', 'Beijing', 'Beijing', 15, 'twizy.png', UNIX_TIMESTAMP()),
       ('Peugeot', 'iOn', 'SMALL', 2, 'AUTOMATIC', 'Shanghai', 'Shanghai', 20, 'ion.png', UNIX_TIMESTAMP()),
       ('Citroen', 'C1', 'SMALL', 2, 'MANUAL', 'Tokyo', 'Tokyo', 25, 'c1.png', UNIX_TIMESTAMP()),
       ('Fiat', 'Panda', 'SMALL', 2, 'MANUAL', 'Osaka', 'Osaka', 30, 'panda.png', UNIX_TIMESTAMP()),
       ('Toyota', 'Camry', 'MEDIUM', 5, 'AUTOMATIC', 'Barcelona', 'Barcelona', 50, 'camry.png', UNIX_TIMESTAMP()),
       ('Ford', 'Mustang', 'MEDIUM', 5, 'MANUAL', 'Copenhagen', 'Copenhagen', 100, 'mustang.png', UNIX_TIMESTAMP()),
       ('Fiat', '500', 'SMALL', 4, 'AUTOMATIC', 'Paris', 'Marseille', 75, 'fiat500.png', UNIX_TIMESTAMP()),
       ('Volkswagen', 'Touran', 'LARGE', 7, 'MANUAL', 'San Francisco', 'Los Angeles', 85, 'touran.png',UNIX_TIMESTAMP()),
       ('Smart', 'Fortwo', 'SMALL', 2, 'AUTOMATIC', 'Miami', 'Orlando', 20, 'fortwo.png', UNIX_TIMESTAMP()),
       ('Honda', 'Civic', 'MEDIUM', 5, 'AUTOMATIC', 'Seattle', 'Portland', 45, 'civic.png', UNIX_TIMESTAMP()),
       ('Chevrolet', 'Impala', 'LARGE', 5, 'AUTOMATIC', 'Dallas', 'Houston', 70, 'impala.png', UNIX_TIMESTAMP()),
       ('Hyundai', 'Elantra', 'MEDIUM', 5, 'MANUAL', 'Denver', 'Salt Lake City', 40, 'elantra.png', UNIX_TIMESTAMP()),
       ('Peugeot', '208', 'SMALL', 4, 'MANUAL', 'Rome', 'Milan', 35, '208.png', UNIX_TIMESTAMP()),
       ('BMW', '3 Series', 'MEDIUM', 5, 'AUTOMATIC', 'Tokyo', 'Osaka', 80, '3series.png', UNIX_TIMESTAMP()),
       ('Audi', 'A4', 'MEDIUM', 5, 'AUTOMATIC', 'Sydney', 'Melbourne', 75, 'a4.png', UNIX_TIMESTAMP()),
       ('Seat', 'Ibiza', 'SMALL', 4, 'MANUAL', 'Barcelona', 'Valencia', 30, 'ibiza.png', UNIX_TIMESTAMP()),
       ('Nissan', 'Altima', 'MEDIUM', 5, 'AUTOMATIC', 'Shanghai', 'Beijing', 55, 'altima.png', UNIX_TIMESTAMP()),
       ('Kia', 'Optima', 'MEDIUM', 5, 'AUTOMATIC', 'Seoul', 'Busan', 50, 'optima.png', UNIX_TIMESTAMP()),
       ('Mazda', '3', 'MEDIUM', 5, 'AUTOMATIC', 'Kyoto', 'Nagoya', 45, 'mazda3.png', UNIX_TIMESTAMP()),
       ('Subaru', 'Impreza', 'MEDIUM', 5, 'MANUAL', 'Sapporo', 'Fukuoka', 40, 'impreza.png', UNIX_TIMESTAMP()),
       ('Volkswagen', 'Touran', 'LARGE', 7, 'MANUAL', 'London', 'Manchester', 85, 'touran.png', UNIX_TIMESTAMP()),
       ('Mercedes-Benz', 'Vito', 'LARGE', 7, 'AUTOMATIC', 'Berlin', 'Hamburg', 90, 'vito.png', UNIX_TIMESTAMP()),
       ('Citroen', 'Berlingo', 'LARGE', 7, 'MANUAL', 'Los Angeles', 'San Francisco', 60, 'berlingo.png', UNIX_TIMESTAMP()),
       ('Peugeot', '5008', 'LARGE', 7, 'MANUAL', 'Paris', 'Nice', 70, '5008.png', UNIX_TIMESTAMP()),
       ('Renault', 'Espace', 'LARGE', 7, 'AUTOMATIC', 'Hamburg', 'Munich', 80, 'espace.png', UNIX_TIMESTAMP()),
       ('Smart', 'Fortwo', 'SMALL', 2, 'AUTOMATIC', 'Berlin', 'Frankfurt', 20, 'fortwo.png', UNIX_TIMESTAMP()),
       ('Fiat', '500', 'SMALL', 2, 'MANUAL', 'Barcelona', 'Valencia', 30, 'fiat500.png', UNIX_TIMESTAMP()),
       ('Toyota', 'iQ', 'SMALL', 2, 'AUTOMATIC', 'Milan', 'Florence', 25, 'iq.png', UNIX_TIMESTAMP()),
       ('Renault', 'Twizy', 'SMALL', 2, 'AUTOMATIC', 'Shanghai', 'Beijing', 15, 'twizy.png', UNIX_TIMESTAMP()),
       ('Peugeot', 'iOn', 'SMALL', 2, 'AUTOMATIC', 'Tokyo', 'Kyoto', 20, 'ion.png', UNIX_TIMESTAMP()),
       ('Citroen', 'C1', 'SMALL', 2, 'MANUAL', 'Sydney', 'Melbourne', 25, 'c1.png', UNIX_TIMESTAMP()),
       ('Fiat', 'Panda', 'SMALL', 2, 'MANUAL', 'Seoul', 'Busan', 30, 'panda.png', UNIX_TIMESTAMP());